name: Push DNS

on:
  push:
    branches:
       - coal
    paths:
      - 'dns/dnsconfig.js'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: DNSControl push
        uses: koenrh/dnscontrol-action@v3
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        with:
          args: push
          
          config_file: 'dns/dnsconfig.js'
          creds_file: 'dns/creds.json'
